In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"sudh" , 34.565, True]

In [5]:
a1 = np.array(l1)

In [6]:
a2 = np.array([[1,2,3] , [4,5,6]])

In [7]:
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [8]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

3

In [14]:
a1.size

7

In [15]:
a2.size

6

In [16]:
a3.size

9

In [17]:
a1.shape

(7,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(1, 3, 3)

In [20]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
np.random.randint(2,50 ,(3,4) )

array([[36, 35, 18, 49],
       [14, 31, 26, 46],
       [21, 16, 23, 25]])

In [24]:
np.random.randint(2,50 ,(2,3,4) )

array([[[49, 48, 16, 25],
        [ 3, 22,  4, 30],
        [15,  7, 49,  3]],

       [[27, 20, 37, 32],
        [18,  4, 35, 12],
        [29, 44, 48, 34]]])

In [25]:
np.random.rand(5,4)

array([[0.13454428, 0.38625731, 0.26025069, 0.77021496],
       [0.1799592 , 0.98448681, 0.59969903, 0.27494463],
       [0.99693563, 0.83754786, 0.45141231, 0.68781233],
       [0.44389796, 0.76237118, 0.71514794, 0.0343742 ],
       [0.59756942, 0.53327682, 0.57721524, 0.08706138]])

In [26]:
a4 =  np.random.randn(4,4)

In [27]:
a4

array([[ 1.28960747, -0.90148295, -0.56536661,  0.57226216],
       [-1.38509972, -1.43676863, -0.03951224, -0.21169411],
       [ 0.03945658,  0.76867339, -1.50116804, -0.35778822],
       [-0.04946324, -2.70958655,  2.03938874, -0.26770579]])

In [28]:
a4.reshape(2,8)

array([[ 1.28960747, -0.90148295, -0.56536661,  0.57226216, -1.38509972,
        -1.43676863, -0.03951224, -0.21169411],
       [ 0.03945658,  0.76867339, -1.50116804, -0.35778822, -0.04946324,
        -2.70958655,  2.03938874, -0.26770579]])

In [29]:
a4.reshape(8,2)

array([[ 1.28960747, -0.90148295],
       [-0.56536661,  0.57226216],
       [-1.38509972, -1.43676863],
       [-0.03951224, -0.21169411],
       [ 0.03945658,  0.76867339],
       [-1.50116804, -0.35778822],
       [-0.04946324, -2.70958655],
       [ 2.03938874, -0.26770579]])

In [30]:
a4.reshape(16,1)

array([[ 1.28960747],
       [-0.90148295],
       [-0.56536661],
       [ 0.57226216],
       [-1.38509972],
       [-1.43676863],
       [-0.03951224],
       [-0.21169411],
       [ 0.03945658],
       [ 0.76867339],
       [-1.50116804],
       [-0.35778822],
       [-0.04946324],
       [-2.70958655],
       [ 2.03938874],
       [-0.26770579]])

In [31]:
a4.reshape(2,-134564364)

array([[ 1.28960747, -0.90148295, -0.56536661,  0.57226216, -1.38509972,
        -1.43676863, -0.03951224, -0.21169411],
       [ 0.03945658,  0.76867339, -1.50116804, -0.35778822, -0.04946324,
        -2.70958655,  2.03938874, -0.26770579]])

In [32]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[ 1.28960747, -0.90148295, -0.56536661,
                 0.57226216],
               [-1.38509972, -1.43676863, -0.03951224,
                -0.21169411]],

              [[ 0.03945658,  0.76867339, -1.50116804,
                -0.35778822],
               [-0.04946324, -2.70958655,  2.03938874,
                -0.26770579]]]]]]]]]])

In [33]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [34]:
a1[0]

'4'

In [35]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [36]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [37]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [38]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [39]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [41]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [42]:
a2[[0,1] , 1:]

array([[2, 3],
       [5, 6]])

In [43]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [44]:
a5 = np.random.randint(2,90 , (6,5))

In [45]:
a5

array([[80, 41, 42, 74, 17],
       [34, 81, 68, 57, 56],
       [59, 11, 18, 70, 41],
       [ 8, 44,  7, 43, 20],
       [41, 18, 77, 70, 66],
       [73, 79,  7, 31, 31]])

In [46]:
a5[a5>40]

array([80, 41, 42, 74, 81, 68, 57, 56, 59, 70, 41, 44, 43, 41, 77, 70, 66,
       73, 79])

In [47]:
a5

array([[80, 41, 42, 74, 17],
       [34, 81, 68, 57, 56],
       [59, 11, 18, 70, 41],
       [ 8, 44,  7, 43, 20],
       [41, 18, 77, 70, 66],
       [73, 79,  7, 31, 31]])

In [48]:
a5[0,1] = 100

In [49]:
a5

array([[ 80, 100,  42,  74,  17],
       [ 34,  81,  68,  57,  56],
       [ 59,  11,  18,  70,  41],
       [  8,  44,   7,  43,  20],
       [ 41,  18,  77,  70,  66],
       [ 73,  79,   7,  31,  31]])

In [50]:
a6 = np.random.randint(0,3 , (3,3))

In [51]:
a7 = np.random.randint(0,3 , (3,3))

In [52]:
a6

array([[0, 2, 0],
       [0, 2, 2],
       [2, 1, 1]])

In [53]:
a7



array([[0, 2, 1],
       [1, 0, 2],
       [1, 0, 0]])

In [54]:
a6*a7

array([[0, 4, 0],
       [0, 0, 4],
       [2, 0, 0]])

In [55]:
a6@a7

array([[2, 0, 4],
       [4, 0, 4],
       [2, 4, 4]])

In [56]:
a6

array([[0, 2, 0],
       [0, 2, 2],
       [2, 1, 1]])

In [57]:
a6+100

array([[100, 102, 100],
       [100, 102, 102],
       [102, 101, 101]])

In [58]:
a6*2

array([[0, 4, 0],
       [0, 4, 4],
       [4, 2, 2]])

In [59]:
a6/0

/tmp/ipykernel_4677/1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
/tmp/ipykernel_4677/1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[nan, inf, nan],
       [nan, inf, inf],
       [inf, inf, inf]])

In [60]:
a6

array([[0, 2, 0],
       [0, 2, 2],
       [2, 1, 1]])

In [61]:
a6**3


array([[0, 8, 0],
       [0, 8, 8],
       [8, 1, 1]])

In [62]:
a8 = np.zeros((4,4))

In [63]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
a9  = np.ones((4,5))

In [65]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [67]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [68]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [70]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [72]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [73]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [74]:
a6.T

array([[0, 0, 2],
       [2, 2, 1],
       [0, 2, 1]])

In [75]:
a6

array([[0, 2, 0],
       [0, 2, 2],
       [2, 1, 1]])

In [76]:
a5

array([[ 80, 100,  42,  74,  17],
       [ 34,  81,  68,  57,  56],
       [ 59,  11,  18,  70,  41],
       [  8,  44,   7,  43,  20],
       [ 41,  18,  77,  70,  66],
       [ 73,  79,   7,  31,  31]])

In [77]:
np.sqrt(a5)

array([[ 8.94427191, 10.        ,  6.4807407 ,  8.60232527,  4.12310563],
       [ 5.83095189,  9.        ,  8.24621125,  7.54983444,  7.48331477],
       [ 7.68114575,  3.31662479,  4.24264069,  8.36660027,  6.40312424],
       [ 2.82842712,  6.63324958,  2.64575131,  6.55743852,  4.47213595],
       [ 6.40312424,  4.24264069,  8.77496439,  8.36660027,  8.1240384 ],
       [ 8.54400375,  8.88819442,  2.64575131,  5.56776436,  5.56776436]])

In [78]:
np.exp(a5)

array([[5.54062238e+34, 2.68811714e+43, 1.73927494e+18, 1.37338298e+32,
        2.41549528e+07],
       [5.83461743e+14, 1.50609731e+35, 3.40427605e+29, 5.68572000e+24,
        2.09165950e+24],
       [4.20121040e+25, 5.98741417e+04, 6.56599691e+07, 2.51543867e+30,
        6.39843494e+17],
       [2.98095799e+03, 1.28516001e+19, 1.09663316e+03, 4.72783947e+18,
        4.85165195e+08],
       [6.39843494e+17, 6.56599691e+07, 2.75851345e+33, 2.51543867e+30,
        4.60718663e+28],
       [5.05239363e+31, 2.03828107e+34, 1.09663316e+03, 2.90488497e+13,
        2.90488497e+13]])

In [79]:
np.log10(a5)

array([[1.90308999, 2.        , 1.62324929, 1.86923172, 1.23044892],
       [1.53147892, 1.90848502, 1.83250891, 1.75587486, 1.74818803],
       [1.77085201, 1.04139269, 1.25527251, 1.84509804, 1.61278386],
       [0.90308999, 1.64345268, 0.84509804, 1.63346846, 1.30103   ],
       [1.61278386, 1.25527251, 1.88649073, 1.84509804, 1.81954394],
       [1.86332286, 1.89762709, 0.84509804, 1.49136169, 1.49136169]])

In [80]:
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [81]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [82]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [83]:
np.logspace(2,4,num=4 , base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns



ModuleNotFoundError: No module named 'seaborn'

In [86]:
!pip install cufflinks

In [87]:
cf.go_offline()

In [88]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [89]:
df

A         B         C
0   0.981034  0.234923  0.174117
1   0.077970 -2.706982  0.367047
2  -0.680587 -0.727142 -1.308643
3  -1.702816  0.261524 -0.028433
4  -1.359926 -0.344664 -0.179341
..       ...       ...       ...
95 -0.355311 -1.022367  0.101641
96  1.194287  1.899108 -0.716645
97  0.226825 -0.379640 -0.593190
98  0.600520  0.113718  2.887098
99 -0.548778 -1.176053 -0.526120

[100 rows x 3 columns]

In [90]:
df.iplot()

In [91]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [92]:
df1

0
0   66
1   62
2   98
3   87
4   90
..  ..
95  88
96   4
97  20
98  39
99  56

[100 rows x 1 columns]

In [93]:
df1.iplot()

In [94]:
df1

0
0   66
1   62
2   98
3   87
4   90
..  ..
95  88
96   4
97  20
98  39
99  56

[100 rows x 1 columns]

In [95]:
df

A         B         C
0   0.981034  0.234923  0.174117
1   0.077970 -2.706982  0.367047
2  -0.680587 -0.727142 -1.308643
3  -1.702816  0.261524 -0.028433
4  -1.359926 -0.344664 -0.179341
..       ...       ...       ...
95 -0.355311 -1.022367  0.101641
96  1.194287  1.899108 -0.716645
97  0.226825 -0.379640 -0.593190
98  0.600520  0.113718  2.887098
99 -0.548778 -1.176053 -0.526120

[100 rows x 3 columns]

In [96]:
df.iplot(x = 'A' , y = 'B',mode = 'markers')

In [99]:
!pip install seaborn

     |████████████████████████████████| 292 kB 329 kB/s eta 0:00:01
     |████████████████████████████████| 43.4 MB 1.3 MB/s eta 0:00:01     |████████████████████████████▊   | 38.9 MB 2.4 MB/s eta 0:00:02
     |████████████████████████████████| 11.3 MB 916 kB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 6.9 MB/s eta 0:00:01
     |████████████████████████████████| 944 kB 3.9 MB/s eta 0:00:01


In [100]:
import seaborn as sns
df2 = sns.load_dataset('titanic')

In [101]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [102]:
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )

In [103]:
df2.iplot(x = 'age' , y ='pclass',mode = 'markers' )

In [104]:
df2.iplot(x = 'fare' , y ='pclass',mode = 'markers' )

In [105]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [106]:
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')